# render.yaml

services:
  - type: web
    name: discord-bot
    env: docker
    dockerfilePath: ./Dockerfile
    # Se seu bot precisar rodar com um comando custom:
    startCommand: python src/main.py
    branch: versao_airflow
    autoDeploy: true
    # Porta para Render detectar saúde do container (se tiver Web UI)
    # healthCheckPath: /
    # Pode configurar CPU/mem e variáveis de ambiente no painel ou aqui

  - type: pserv       # Persistent Service para Airflow
    name: airflow-service
    env: docker
    dockerfilePath: ./Dockerfile
    branch: versao_airflow
    autoDeploy: true
    startCommand: astro dev start
    disk:
      name: airflow-data-volume
      mountPath: /app/data
      sizeGB: 1
